"""changed tables

Revision ID: 9f2c0e09d810
Revises: 8ed51fbe871f
Create Date: 2023-05-11 18:52:16.539136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2c0e09d810'
down_revision = '8ed51fbe871f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
